# =========================
# NETWORK
# =========================

bind 0.0.0.0
protected-mode no 
port 6379
# Production 
# protected-mode yes
# requirepass YOUR_STRONG_PASSWORD

# =========================
# PERSISTENCE
# =========================

appendonly yes
appendfsync everysec

# AOF rewrite optimization
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Optional RDB snapshots
save 900 1
save 300 10
save 60 10000

# =========================
# MEMORY
# =========================

# Max RAM Usage
maxmemory 512mb

# Safer for Laravel mixed usage
maxmemory-policy volatile-lru

# =========================
# LOGGING
# =========================

loglevel notice

# ==========================================
# SECURITY
# ==========================================

# Disable dangerous commands
rename-command FLUSHALL ""
rename-command FLUSHDB ""


# =========================
# DATA DIRECTORY
# =========================

dir /data