server {
    # Port/ name/ max upload
    listen 80; 
    server_name localhost;
    client_max_body_size 500M;

    # Laravel entry point is /public
    root /var/www/public;

    # Default file to serve
    index index.php;

    # Try to serve:
    # 1. exact file
    # 2. directory
    # 3. fallback to Laravel index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Match any .php file request
    location ~ \.php$ {

        # Send request to PHP container (service name = "app")
        # port 9000 = PHP-FPM listens here :contentReference[oaicite:1]{index=1}
        fastcgi_pass app:9000;

        # Standard FastCGI config (headers, etc.)
        include fastcgi_params;

        # Tell PHP exactly which file to execute
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}